" user configuration
syntax on
set cindent
set nu
set relativenumber
set tabstop=4
set shiftwidth=4
colorscheme evening
set guifont=Consolas:b:h12
" set background=dark
" inoremap ( ()<LEFT>
" inoremap [ []<LEFT>
inoremap { {}<LEFT><ENTER><ENTER><UP>
inoremap <C-A> <ESC>ggvG$"+y
inoremap <F5> <ESC>:call Run()<CR>

map <C-A> ggvG$"+y
map <F5> :call Run()<CR>
func! Run()
	exec "w"
	exec "!g++ -Wall -g % -o %<.exe"
	exec "silent !%<.exe < my.in > my.out"
endfunc

